-- MySQL Script generated by MySQL Workbench
-- Mon Sep 30 23:05:08 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema parcial1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema parcial1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `parcial1` DEFAULT CHARACTER SET utf8 ;
USE `parcial1` ;

-- -----------------------------------------------------
-- Table `parcial1`.`Producers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `parcial1`.`Producers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `lastName` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
